language: node_js
node_js: '12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls
deploy:
  provider: heroku
  api_key:
    secure: 581a3079-e74b-438b-9545-75faf473c126
  app: dttnotetaker